site_name: Heavy Setup
site_description: My personal Truenas SCALE application setups
site_author: Heavybullets8
site_url: https://heavybullets8.github.io/HeavySetup/

repo_url: https://github.com/Heavybullets8/HeavySetup
repo_name: HeavySetup
     
plugins:
    - search
    - awesome-pages
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: indigio
      accent: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode