site_name: Heavy Setup
site_description: My personal Truenas SCALE application setups
site_author: Heavybullets8
site_url: https://heavybullets8.github.io/HeavySetup/

repo_url: https://github.com/Heavybullets8/HeavySetup
repo_name: HeavySetup

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
plugins:
    - search
    - awesome-pages
    - mkdocs-video
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: blue gray
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: white
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode